=== Cannabytes/SphereWebPremium/data/resources/datapacks/lucera3/items/item.dtd
<!ELEMENT list (weapon|etcitem|armor)*>
<!ELEMENT weapon  (set|equip|for|enchant4_skill|cond|skills|triggers|attributes|enchant_options)*>
<!ATTLIST weapon
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>
<!ELEMENT etcitem (set|equip|for|enchant4_skill|cond|skills|triggers|enchant_options)*>
<!ATTLIST etcitem
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>
<!ELEMENT armor  (set|equip|for|enchant4_skill|cond|skills|triggers|attributes|enchant_options)*>
<!ATTLIST armor
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>

<!ELEMENT enchant_options (level)*>
<!ELEMENT level (option)*>
<!ATTLIST level
	val CDATA #REQUIRED>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
	id CDATA #REQUIRED>

<!ELEMENT equip (slot)*>
<!ELEMENT slot (#PCDATA)>
<!ATTLIST slot
	id CDATA #REQUIRED>

<!ELEMENT cond (player|target|using|zone|or|not|and)*>
<!ATTLIST cond
	msgId CDATA #IMPLIED
	customMessage CDATA #IMPLIED
	addName CDATA #IMPLIED>
<!ELEMENT or (player|target|using|zone|not|and)*>
<!ELEMENT not (player|target|using|zone|or|and)*>
<!ELEMENT and (player|target|using|zone|or|not)*>
<!ELEMENT player (#PCDATA)>
<!ATTLIST player
	residence CDATA #IMPLIED
	olympiad CDATA #IMPLIED
	on_pvp_event CDATA #IMPLIED
	is_in_combat CDATA #IMPLIED
	race CDATA #IMPLIED
	instance_zone CDATA #IMPLIED
	classId CDATA #IMPLIED
    minLevel CDATA #IMPLIED
    maxLevel CDATA #IMPLIED
	is_hero  CDATA #IMPLIED
	maxPK  CDATA #IMPLIED
	min_pledge_rank  CDATA #IMPLIED
	castleId  CDATA #IMPLIED
	is_clan_leader  CDATA #IMPLIED
	is_in_academy  CDATA #IMPLIED
	has_pet CDATA #IMPLIED
	mounted CDATA #IMPLIED
    gender CDATA #IMPLIED>
<!ELEMENT target (#PCDATA)>
<!ATTLIST target
	pvp CDATA #REQUIRED>
<!ELEMENT using (#PCDATA)>
<!ATTLIST using
	slotitem CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	type CDATA #REQUIRED>

<!ELEMENT for (add|set|mul|enchant)*>
<!ELEMENT add (player|target|using|zone|or|not|and)*>
<!ATTLIST add
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT attributes (attribute)*>
<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute
	element CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT mul (player|target|using|zone)*>
<!ATTLIST mul
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT set (player|target|using|zone|or|not|and)*>
<!ATTLIST set
	name CDATA #IMPLIED
	order CDATA #IMPLIED
	stat CDATA #IMPLIED
	value CDATA #REQUIRED>

<!ELEMENT enchant (#PCDATA)>
<!ATTLIST enchant
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT enchant4_skill (#PCDATA)>
<!ATTLIST enchant4_skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>

<!ELEMENT skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>

<!ELEMENT triggers (trigger)*>
<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	type CDATA #REQUIRED
	chance CDATA #REQUIRED>

=== Cannabytes/SphereWebPremium/data/resources/datapacks/lucera3/items/3000-3099.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">

<list>
  <etcitem id="3000" name="Recipe: Dwarven Chain Shield">
    <!-- [rp_dwarven_chain_shield] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="3120"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3001" name="Recipe: Rind Leather Boots">
    <!-- [rp_rind_leather_boots] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="3220"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3002" name="Recipe: Dwarven Chain Gloves">
    <!-- [rp_dwarven_chain_gloves] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="3220"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3003" name="Recipe: Gloves of Seal">
    <!-- [rp_gloves_of_seal] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="3220"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3004" name="Recipe: Rind Leather Gloves">
    <!-- [rp_rind_leather_gloves] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="3220"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3005" name="Recipe: Demon's Boots">
    <!-- [rp_demon_s_boots] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="4900"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3006" name="Recipe: Demon's Gloves">
    <!-- [rp_demon_s_gloves] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="4900"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3007" name="Recipe: Theca Leather Boots">
    <!-- [rp_theca_leather_boots] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="5500"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3008" name="Recipe: Theca Leather Gloves">
    <!-- [rp_theca_leather_gloves] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="5500"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3009" name="Recipe: Composite Boots">
    <!-- [rp_composite_boots] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="4900"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3010" name="Recipe: Composite Helmet">
    <!-- [rp_composite_helmet] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="7360"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3011" name="Recipe: Divine Boots">
    <!-- [rp_divine_boots] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="7160"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3012" name="Recipe: Full Plate Helmet">
    <!-- [rp_full_plate_helmet] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="10720"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3013" name="Recipe: Drake Leather Boots">
    <!-- [rp_drake_leather_boots] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="7160"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3014" name="Recipe: Full Plate Boots">
    <!-- [rp_full_plate_boots] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="7160"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3015" name="Recipe: Drake Leather Gloves">
    <!-- [rp_drake_leather_gloves] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="7160"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3016" name="Recipe: Full Plate Gauntlets">
    <!-- [rp_full_plate_gauntlet] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="7160"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3017" name="Recipe: Divine Gloves">
    <!-- [rp_blessed_gloves] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="7160"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3018" name="Recipe: Blessed Gloves">
    <!-- [rp_divine_gloves] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="7160"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3019" name="Recipe: Full Plate Shield">
    <!-- [rp_full_plate_shield] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="7500"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3020" name="Recipe: Elven Long Sword">
    <!-- [rp_elven_long_sword] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_blue_i00"/>
    <set name="price" value="36000"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3021" name="Recipe: Dwarven War Hammer">
    <!-- [rp_dwarven_warhammer] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="57400"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3022" name="Recipe: Yaksa Mace">
    <!-- [rp_yaksa_mace] -->
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_yellow_i00"/>
    <set name="price" value="122600"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3023" name="Recipe: Titan Key">
    <!-- [rp_titan_key] -->
    <set name="tradeable" value="false"/>
    <set name="dropable" value="false"/>
    <set name="destroyable" value="false"/>
    <set name="class" value="RECIPIES"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_recipe_blue_i00"/>
    <set name="stackable" value="true"/>
    <set name="type" value="RECIPE"/>
    <set name="weight" value="30"/>
  </etcitem>
  <etcitem id="3024" name="Recipe: Journeyman Ring">
    <!-- [rp_journeyman_ring] -->
    <set name="tradeable" value="false"/>
    <set name="dropable" value="false"/>
    <set name="destroyable" value="false"/>
    <set name="class" value="RECIPIES"/>
